### PR TITLE
Replace use of +new with +alloc and -init

### PR DESCRIPTION
**Pull request by elitalon**
This addresses #5 by replacing `+new` with the combo `+alloc` and `-init`.

### CODE REVIEW

**Comment by blakewatters** [comment]
That is a super irritating and totally unnecessary API change. Why does `alloc` and `init` work? Seems like you would only do this if there was a designated initializer

**Comment by elitalon** [comment]
Hey, sorry for getting back to this so late.

I don't understand quite well the issue either. I discovered it while working on layerhq/Atlas-iOS#1275. I will try to setup a separate project and see where this comes from.

**Comment by elitalon** [comment]
I was able to reproduce the issue with a sample project using only KIF and KIFViewControllerActions as dependencies.

The compiler is complaining because of these two lines in [`KIFTestActor.h`](https://github.com/kif-framework/KIF/blob/v3.5.0/Classes/KIFTestActor.h#L85):

```objc
+ (instancetype)new NS_UNAVAILABLE;
- (instancetype)init NS_UNAVAILABLE;
```

If we mark `+alloc` as unavailable as well, then the compiler will also complain about using `[[viewControllerClass alloc] init]`.

My guess is that `+alloc` returns an instance of `UIViewController` instead of `KIFTestActor`, therefore allowing to call `-init`.

Another discussion is why I'm having this issue if the [Atlas's Podfile.lock on 1.0.29](https://github.com/layerhq/Atlas-iOS/blob/v1.0.29/Podfile.lock#L7) states that it should be using [KIF 3.4.2](https://github.com/kif-framework/KIF/releases/tag/v3.4.2), which doesn't have those redefinitions.

**Review by kunalbalani — APPROVED** [review]
I tested this works

**Comment by kunalbalani** [comment]
+1 for the change 👍

**Comment by kunalbalani** [comment]
@blakewatters can you please approve the changes ?

**Comment by armcknight** [comment]
This is actually not correct as `initWithNib:bundle:` is the designated initializer for `UIViewController`.

**Comment by armcknight** [comment]
closed in favor of #7

**Pull request closed without merging**
